apiVersion: apps/v1
kind: Deployment
metadata:
  name: swiggy-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: swiggy
      version: blue
  template:
    metadata:
      labels:
        app: swiggy
        version: blue
    spec:
      containers:
      - name: swiggy-container
        image: mydocker3692/swiggy-v1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
