apiVersion: apps/v1
kind: Deployment
metadata:
  name: swiggy-green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: swiggy
      version: green
  template:
    metadata:
      labels:
        app: swiggy
        version: green
    spec:
      containers:
      - name: swiggy-container
        image: mydocker3692/swiggy-clone:IMAGE_TAG
        imagePullPolicy: Always
        ports:
        - containerPort: 80
