apiVersion: v1
kind: Service
metadata:
  name: swiggy-service
spec:
  type: NodePort
  selector:
    app: swiggy
    version: blue   # <-- Initially point to BLUE
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007
